config/routes.rb
Rails.application.routes.draw do
  resources :welcomes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'welcomes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/welcome.rb
class Welcome < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  before_action :set_welcome, only: %i[ show edit update destroy ]

  # GET /welcomes or /welcomes.json
  def index
    @welcomes = Welcome.all
  end

  # GET /welcomes/1 or /welcomes/1.json
  def show
  end

  # GET /welcomes/new
  def new
    @welcome = Welcome.new
  end

  # GET /welcomes/1/edit
  def edit
  end

  # POST /welcomes or /welcomes.json
  def create
    @welcome = Welcome.new(welcome_params)

    respond_to do |format|
      if @welcome.save
        format.html { redirect_to welcome_url(@welcome), notice: "Welcome was successfully created." }
        format.json { render :show, status: :created, location: @welcome }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /welcomes/1 or /welcomes/1.json
  def update
    respond_to do |format|
      if @welcome.update(welcome_params)
        format.html { redirect_to welcome_url(@welcome), notice: "Welcome was successfully updated." }
        format.json { render :show, status: :ok, location: @welcome }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /welcomes/1 or /welcomes/1.json
  def destroy
    @welcome.destroy

    respond_to do |format|
      format.html { redirect_to welcomes_url, notice: "Welcome was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_welcome
      @welcome = Welcome.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def welcome_params
      params.fetch(:welcome, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ychung</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcomes/_form.html.erb
<%= form_with(model: welcome) do |form| %>
  <% if welcome.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(welcome.errors.count, "error") %> prohibited this welcome from being saved:</h2>

      <ul>
        <% welcome.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/welcomes/_welcome.html.erb
<div id="<%= dom_id welcome %>">
</div>

app/views/welcomes/edit.html.erb
<h1>Editing welcome</h1>

<%= render "form", welcome: @welcome %>

<br>

<div>
  <%= link_to "Show this welcome", @welcome %> |
  <%= link_to "Back to welcomes", welcomes_path %>
</div>

app/views/welcomes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Welcomes</h1>
  <p>
    The time is now: <%= Time.now %>
  </p>
<div id="welcomes">
  <% @welcomes.each do |welcome| %>
    <%= render welcome %>
    <p>
      <%= link_to "Show this welcome", welcome %>
    </p>
  <% end %>
</div>

<%= link_to "New welcome", new_welcome_path %>

app/views/welcomes/new.html.erb
<h1>New welcome</h1>

<%= render "form", welcome: @welcome %>

<br>

<div>
  <%= link_to "Back to welcomes", welcomes_path %>
</div>

app/views/welcomes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @welcome %>

<div>
  <%= link_to "Edit this welcome", edit_welcome_path(@welcome) %> |
  <%= link_to "Back to welcomes", welcomes_path %>

  <%= button_to "Destroy this welcome", @welcome, method: :delete %>
</div>